### ISSUE TITLE
VPS Deployment Checklist

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#231]
- [ ] NGINX Reverse Proxy & [https://nginxconfig.io/](https://nginxconfig.io/)
- [ ] PM2
- [ ] HTTPS
- [ ] Fail2ban [Help](https://www.linode.com/docs/security/using-fail2ban-to-secure-your-server-a-tutorial/)
- [ ] Gzip Compression
- [ ] Let’s Encrypt Auto Renewal
- [ ] MongoDB
