### ISSUE TITLE
VPS Deployment Checklist

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#233]
- [x] NGINX Reverse Proxy & [https://nginxconfig.io/](https://nginxconfig.io/)
- [x] PM2
- [x] HTTPS
- [x] MongoDB
- [x] Fail2ban [Help](https://www.linode.com/docs/security/using-fail2ban-to-secure-your-server-a-tutorial/)
- [x] Let’s Encrypt Auto Renewal
- [x] Gzip Compression
- [x] Nodejs
